### ISSUE TITLE
Change notification Sound

### ISSUE THREAD

**Issue by aalmenar** [tanelpuhu/pushover-for-chrome#3]
It would be nice if in extension configuration one could change or select the sound to be used when receiving pushes from this extension.

Thanks

**Comment by tanelpuhu** [comment]
I've added sound selection (21 different ones that are described in https://pushover.net/api#sounds) and uploaded new version to Chrome Web Store... seems to work for me 😄  

(Odd that I have not received notification for this issue, only today noticed it.)

**Comment by tanelpuhu** [comment]
Works for me, by now (if you still use this plugin 😄 ) it should be updated for you also, please see the Options page.
