### ISSUE TITLE
'url' field in API not set if it's not a selection

### ISSUE THREAD

**Issue by mikerubits** [tanelpuhu/pushover-for-chrome#5]
```
    if (selection) {
        params += '&message=' + encodeURIComponent(selection.substring(0, 512));
        params += '&url=' + encodeURIComponent(tab.url.substring(0, 500));
    } else {
        params += '&message=' + encodeURIComponent(tab.url.substring(0, 500));
    }
```

The url parameter isn't set if there's not a text selection. This causes the "Auto-open URLs" feature in the app to not work unless you select some text before hitting send every time.

**Comment by tanelpuhu** [comment]
Oh... I wasn't aware there was such option... on iOS only? Also _discovered_  that the "Open..." link does not appear in notification drawer also then... 😞  Maybe the same thing 😄 ? 

Anyway, as the _message_ is required parameter I must have just dropped it (the URL) there and when I made the selection _feature_, just added the code above... I'm open to suggestions... adding the **url_title** is one option.... so... something like following should solve the issue for you?

Before:
![screenshot 2016-09-29 18 18 09](https://cloud.githubusercontent.com/assets/19875/18960110/3ed39eba-8671-11e6-953e-313881ce76f7.png)

After:
![screenshot 2016-09-29 18 16 06](https://cloud.githubusercontent.com/assets/19875/18960108/3ecf4a86-8671-11e6-9ba2-7425ec6603a5.png)

... and it's nice in notification drawer also (I don't have iOS device, dunno how its displayed there)
![screenshot 2016-09-29 18 15 54](https://cloud.githubusercontent.com/assets/19875/18960109/3ed29b5a-8671-11e6-86a6-8f3f61838545.png)

Diff:
```
diff --git a/background.js b/background.js
index 7882550..91f1064 100644
--- a/background.js
+++ b/background.js
@@ -55,6 +55,8 @@ push_message = function(source, tab, selection, device) {
         params += '&url=' + encodeURIComponent(tab.url.substring(0, 500));
     } else {
         params += '&message=' + encodeURIComponent(tab.url.substring(0, 500));
+        params += '&url=' + encodeURIComponent(tab.url.substring(0, 500));
+        params += '&url_title=' + encodeURIComponent('Open the link');
     }

     if (localStorage.sound) {
```

PS. the wording "Open the link" might also be weird

**Comment by sponge** [comment]
Yup, that looks right! Probably wouldn't hurt to have url_title in the selection, too. I would think the only thing you would want to switch depending on if (selection) would be the message parameter, and always pass the same url/url_title, but that's minor. url_title seems right too. (same person as reporter, was just on wrong account)

**Comment by tanelpuhu** [comment]
Valid point, lets see if it works 😄

**Comment by tanelpuhu** [comment]
Ups, this is still open... it should be working now, please reopen if still issue for you 😉
